### ISSUE TITLE
npm run start

### ISSUE THREAD

**Issue by alminchen** [wocwin/wocwin-qiankun-v3#1]
<img width="301" alt="image" src="https://github.com/user-attachments/assets/12b0abd2-ae43-4738-9d66-613869252636">
运行start 无法启动项目

pnpm run start:vue2 单独运行 vue2 项目 报错
<img width="573" alt="image" src="https://github.com/user-attachments/assets/bb156159-16dd-4317-99bb-e1e36be5e3da">

**Comment by wocwin** [comment]
前提条件：你每个子应用的依赖有没有安装好，npm run install 无法成功后，就单个应用里面去安装

**Comment by alminchen** [comment]
已经搞好了.跟你类似的思路处理
